src/Shop.Web/ViewComponents/HeaderViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Features.SiteSeting.Requests.Queries;

namespace Shop.Web.ViewComponents
{
    [ViewComponent(Name = "Header")]
    public class HeaderViewComponent : ViewComponent
    {

        private readonly IMediator _mediator;
        public HeaderViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await _mediator.Send(new GetSettingAndSeoQueryReq());
            return View(result);
        }
    }
}

src/Shop.Web/ViewComponents/UserNameViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.DTOs.User;
using Shop.Application.Features.User.Requests.Queries;

namespace Shop.Web.ViewComponents
{
    [ViewComponent(Name = "UserName")]
    public class UserNameViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;
        public UserNameViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync(UserNameDto param)
        {
            var userInfo = await _mediator.Send(new GetUserInfoQueryReq(param.userName, param.Position));
            return View(userInfo);
        }
    }
}

src/Shop.Web/Pages/Shared/Auth_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <title>مدیریت</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="پنل مدیریت  ">
    <meta name="keywords" content="digichad">
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- BEGIN CSS -->
    <partial name="Admin/_Css"></partial>
    @await RenderSectionAsync("Styles",required:false);
    <!-- END CSS -->


</head>
<body class="fix-header active-ripple theme-blue">
    <!-- BEGIN LOEADING -->
    <div id="loader">
        <div class="spinner"></div>
    </div><!-- /loader -->
    <!-- END LOEADING -->
    <!-- BEGIN WRAPPER -->
    <div class="fixed-modal-bg"></div>
    
    <div class="modal-page shadow">
        @RenderBody()
    </div><!-- /.modal-page -->
    <!-- END WRAPPER -->
    <!-- BEGIN JS -->
    <partial name="Admin/_Js"></partial>

    <!-- BEGIN PAGE JAVASCRIPT -->
    <script src="~/Admin/js/pages/login.js"></script>
    @await RenderSectionAsync("Scripts",required:false);
    <!-- END PAGE JAVASCRIPT -->

</body>
</html>

src/Shop.Web/Pages/Shared/SiteAuth_Layout.cshtml
<html lang="en">
<head>
    <!-- Title -->
    @await Component.InvokeAsync("Header")
    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @await RenderSectionAsync("Meta", required: false)
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <partial name="Site/Header/_Css" />
    @await RenderSectionAsync("Styles", required: false)
</head>

<body>

   
    <!-- ========== MAIN CONTENT ========== -->
    @RenderBody()
    



    <!-- JS Global Compulsory -->
    <form method="post"></form>
    <script src="~/Admin/plugins/bootstrap/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <script src="~/Site/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/Site/vendor/jquery-migrate/dist/jquery-migrate.min.js"></script>
    <script src="~/Site/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/Site/vendor/bootstrap/bootstrap.min.js"></script>

    <!-- JS Implementing Plugins -->
    <script src="~/Site/vendor/appear.js"></script>
    <script src="~/Site/vendor/jquery.countdown.min.js"></script>
    <script src="~/Site/vendor/hs-megamenu/src/hs.megamenu.js"></script>
    <script src="~/Site/vendor/svg-injector/dist/svg-injector.min.js"></script>
    <script src="~/Site/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Site/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/Site/vendor/fancybox/jquery.fancybox.min.js"></script>
    <script src="~/Site/vendor/slick-carousel/slick/slick.js"></script>
    <script src="~/Site/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>

    <!-- JS Electro -->
    <script src="~/Site/js/hs.core.js"></script>
    <script src="~/Site/js/components/hs.countdown.js"></script>
    <script src="~/Site/js/components/hs.header.js"></script>
    <script src="~/Site/js/components/hs.hamburgers.js"></script>
    <script src="~/Site/js/components/hs.unfold.js"></script>
    <script src="~/Site/js/components/hs.focus-state.js"></script>
    <script src="~/Site/js/components/hs.malihu-scrollbar.js"></script>
    <script src="~/Site/js/components/hs.validation.js"></script>
    <script src="~/Site/js/components/hs.fancybox.js"></script>
    <script src="~/Site/js/components/hs.onscroll-animation.js"></script>
    <script src="~/Site/js/components/hs.slick-carousel.js"></script>
    <script src="~/Site/js/components/hs.show-animation.js"></script>
    <script src="~/Site/js/components/hs.svg-injector.js"></script>
    <script src="~/Site/js/components/hs.go-to.js"></script>
    <script src="~/Site/js/components/hs.selectpicker.js"></script>
    <script src="~/Admin/plugins/sweetalert2/dist/sweetalert2.min.js"></script>
    <script src="~/Shared/Lib/Shared/All/All.js"></script>
    <script src="~/Shared/Lib/Shared/All/Identity.js"></script>
    @*<script src="~/Admin/js/pages/swal.js"></script>*@
    <link href="~/Ahared/Lib/Shared/Css/Table.css" rel="stylesheet" />


    <!-- JS Plugins Init. -->
    <script>
        $(window).on('load', function () {
            // initialization of HSMegaMenu component
            $('.js-mega-menu').HSMegaMenu({
                event: 'hover',
                direction: 'horizontal',
                pageContainer: $('.container'),
                breakpoint: 1199.98,
                hideTimeOut: 0
            });

            // initialization of svg injector module
            $.HSCore.components.HSSVGIngector.init('.js-svg-injector');
        });

        $(document).on('ready', function () {
            // initialization of header
            $.HSCore.components.HSHeader.init($('#header'));

            // initialization of animation
            $.HSCore.components.HSOnScrollAnimation.init('[data-animation]');

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
                afterOpen: function () {
                    $(this).find('input[type="search"]').focus();
                }
            });

            // initialization of popups
            $.HSCore.components.HSFancyBox.init('.js-fancybox');

            // initialization of countdowns
            var countdowns = $.HSCore.components.HSCountdown.init('.js-countdown', {
                yearsElSelector: '.js-cd-years',
                monthsElSelector: '.js-cd-months',
                daysElSelector: '.js-cd-days',
                hoursElSelector: '.js-cd-hours',
                minutesElSelector: '.js-cd-minutes',
                secondsElSelector: '.js-cd-seconds'
            });

            // initialization of malihu scrollbar
            $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

            // initialization of forms
            $.HSCore.components.HSFocusState.init();

            // initialization of form validation
            $.HSCore.components.HSValidation.init('.js-validate', {
                rules: {
                    confirmPassword: {
                        equalTo: '#signupPassword'
                    }
                }
            });

            // initialization of show animations
            $.HSCore.components.HSShowAnimation.init('.js-animation-link');

            // initialization of fancybox
            $.HSCore.components.HSFancyBox.init('.js-fancybox');

            // initialization of slick carousel
            $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');

            // initialization of go to
            $.HSCore.components.HSGoTo.init('.js-go-to');

            // initialization of hamburgers
            $.HSCore.components.HSHamburgers.init('#hamburgerTrigger');

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
                beforeClose: function () {
                    $('#hamburgerTrigger').removeClass('is-active');
                },
                afterClose: function () {
                    $('#headerSidebarList .collapse.show').collapse('hide');
                }
            });

            $('#headerSidebarList [data-toggle="collapse"]').on('click', function (e) {
                e.preventDefault();

                var target = $(this).data('target');

                if ($(this).attr('aria-expanded') === "true") {
                    $(target).collapse('hide');
                } else {
                    $(target).collapse('show');
                }
            });

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));

            // initialization of select picker
            $.HSCore.components.HSSelectPicker.init('.js-select');
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

src/Shop.Web/Pages/Shared/_Layout.cshtml
<html lang="en">
<head>
    <!-- Title -->
    @await Component.InvokeAsync("Header")
    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @await RenderSectionAsync("Meta", required: false)
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <partial name="Site/Header/_Css" />
    @await RenderSectionAsync("Styles", required: false)
</head>

<body>

    <!-- ========== HEADER ========== -->
    <header id="header" class="u-header u-header-left-aligned-nav mb-3">
        <div class="u-header__section shadow-none">
            <!-- Topbar -->
            <partial name="Site/Header/_Toolbar" />
            <!-- End Topbar -->
            <!-- Logo-Vertical-menu-Search-header-icons -->
            <div class="border-bottom border-lg-down-0  bg-xl-transparent min-height-64 flex-horizontal-center">
                <div class="container ">
                    <div class="row align-items-center justify-content-between justify-content-xl-start">


                        <!-- Header Icons -->
                        <partial name="Site/Header/_Icons" />
                        <!-- End Header Icons -->
                        <!-- Search Bar -->
                        <partial name="Site/Header/_SearchBox" />
                        <!-- End Search Bar -->
                        <!-- Logo -->
                        <partial name="Site/Header/_LogoCategories" />
                        <!-- End Logo -->
                    </div>
                </div>

            </div>
            <!-- End Logo-Vertical-menu-Search-header-icons -->
            <!-- Secondary-menu -->
            @*<partial name="Site/Header/_SubMenu"/>*@
            <!-- End Secondary-menu -->
        </div>
    </header>
    <!-- ========== END HEADER ========== -->
    <!-- ========== MAIN CONTENT ========== -->
    @RenderBody()
    <!-- ========== END MAIN CONTENT ========== -->
    <!-- ========== FOOTER ========== -->
    <partial name="Site/Footer/_FooterPartial" />
    <!-- ========== END FOOTER ========== -->
    <!-- ========== SECONDARY CONTENTS ========== -->
    <!-- Mobile Nav -->
    <div class="MobileMenu nav-bottom position-fixed bottom-0 end-0 w-100  align-items-center justify-content-between bg-gray-7 p-5 border-color-1  productImageBackRadius">

        <partial name="Shared/_UserNamePartialMobileMenu" />
    </div>



    <!-- JS Global Compulsory -->
    <form method="post"></form>
    <script src="~/Admin/plugins/bootstrap/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <script src="~/Site/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/Site/vendor/jquery-migrate/dist/jquery-migrate.min.js"></script>
    <script src="~/Site/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/Site/vendor/bootstrap/bootstrap.min.js"></script>

    <!-- JS Implementing Plugins -->
    @* <script src="~/Site/vendor/appear.js"></script> *@
    <script src="~/Site/vendor/jquery.countdown.min.js"></script>
    <script src="~/Site/vendor/hs-megamenu/src/hs.megamenu.js"></script>
    @* <script src="~/Site/vendor/svg-injector/dist/svg-injector.min.js"></script> *@
    <script src="~/Site/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    @* <script src="~/Site/vendor/jquery-validation/dist/jquery.validate.min.js"></script> *@
    @* <script src="~/Site/vendor/fancybox/jquery.fancybox.min.js"></script> *@
    <script src="~/Site/vendor/slick-carousel/slick/slick.js"></script>
    <script src="~/Site/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>

    <!-- JS Electro -->
    <script src="~/Site/js/hs.core.js"></script>
    <script src="~/Site/js/components/hs.countdown.js"></script>
    <script src="~/Site/js/components/hs.header.js"></script>
    <script src="~/Site/js/components/hs.hamburgers.js"></script>
    <script src="~/Site/js/components/hs.unfold.js"></script>
    <script src="~/Site/js/components/hs.focus-state.js"></script>
    <script src="~/Site/js/components/hs.malihu-scrollbar.js"></script>
    <script src="~/Site/js/components/hs.validation.js"></script>
    <script src="~/Site/js/components/hs.fancybox.js"></script>
    <script src="~/Site/js/components/hs.onscroll-animation.js"></script>
    <script src="~/Site/js/components/hs.slick-carousel.js"></script>
    <script src="~/Site/js/components/hs.show-animation.js"></script>
    <script src="~/Site/js/components/hs.svg-injector.js"></script>
    <script src="~/Site/js/components/hs.go-to.js"></script>
    <script src="~/Site/js/components/hs.selectpicker.js"></script>
    <script src="~/Admin/plugins/sweetalert2/dist/sweetalert2.min.js"></script>
    <script src="~/Shared/Lib/Shared/All/All.js"></script>
    <script src="~/Shared/Lib/Shared/All/Identity.js"></script>
    @*<script src="~/Admin/js/pages/swal.js"></script>*@
    <link href="~/Shared/Lib/Shared/Cs/Table.css" rel="stylesheet" />


    <!-- JS Plugins Init. -->
    <script>
        $(window).on('load', function () {
            // initialization of HSMegaMenu component
            $('.js-mega-menu').HSMegaMenu({
                event: 'hover',
                direction: 'horizontal',
                pageContainer: $('.container'),
                breakpoint: 1199.98,
                hideTimeOut: 0
            });

            // initialization of svg injector module
            $.HSCore.components.HSSVGIngector.init('.js-svg-injector');
        });

        $(document).on('ready', function () {
            // initialization of header
            $.HSCore.components.HSHeader.init($('#header'));

            // initialization of animation
            $.HSCore.components.HSOnScrollAnimation.init('[data-animation]');

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
                afterOpen: function () {
                    $(this).find('input[type="search"]').focus();
                }
            });

            // initialization of popups
            $.HSCore.components.HSFancyBox.init('.js-fancybox');

            // initialization of countdowns
            var countdowns = $.HSCore.components.HSCountdown.init('.js-countdown', {
                yearsElSelector: '.js-cd-years',
                monthsElSelector: '.js-cd-months',
                daysElSelector: '.js-cd-days',
                hoursElSelector: '.js-cd-hours',
                minutesElSelector: '.js-cd-minutes',
                secondsElSelector: '.js-cd-seconds'
            });

            // initialization of malihu scrollbar
            $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

            // initialization of forms
            $.HSCore.components.HSFocusState.init();

            // initialization of form validation
            $.HSCore.components.HSValidation.init('.js-validate', {
                rules: {
                    confirmPassword: {
                        equalTo: '#signupPassword'
                    }
                }
            });

            // initialization of show animations
            $.HSCore.components.HSShowAnimation.init('.js-animation-link');

            // initialization of fancybox
            $.HSCore.components.HSFancyBox.init('.js-fancybox');

            // initialization of slick carousel
            $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');

            // initialization of go to
            $.HSCore.components.HSGoTo.init('.js-go-to');

            // initialization of hamburgers
            $.HSCore.components.HSHamburgers.init('#hamburgerTrigger');

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
                beforeClose: function () {
                    $('#hamburgerTrigger').removeClass('is-active');
                },
                afterClose: function () {
                    $('#headerSidebarList .collapse.show').collapse('hide');
                }
            });

            $('#headerSidebarList [data-toggle="collapse"]').on('click', function (e) {
                e.preventDefault();

                var target = $(this).data('target');

                if ($(this).attr('aria-expanded') === "true") {
                    $(target).collapse('hide');
                } else {
                    $(target).collapse('show');
                }
            });

            // initialization of unfold component
            $.HSCore.components.HSUnfold.init($('[data-unfold-target]'));

            // initialization of select picker
            $.HSCore.components.HSSelectPicker.init('.js-select');
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

src/Shop.Web/Pages/Shared/_UserNamePartial.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    Param.userName = User.Identity.Name;
    Param.Position = "";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialMenu.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    Param.userName = User.Identity.Name;
    Param.Position = "Menu";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialMobileMenu.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    if (User.Identity.IsAuthenticated)
    {
        Param.userName = User.Identity.Name;
    }
    else
    {
        Param.userName = null;
    }

    Param.Position = "MobileMenu";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialSideBar.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    Param.userName = User.Identity.Name;
    Param.Position = "SideBar";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialSite.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    if (User.Identity.IsAuthenticated)
    {
        Param.userName = User.Identity.Name;
    }
    else
    {
        Param.userName = null;
    }

    Param.Position = "Site";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialSiteMenu.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    if (User.Identity.IsAuthenticated)
    {
        Param.userName = User.Identity.Name;
    }
    else
    {
        Param.userName = null;
    }

    Param.Position = "SiteMenu";
}
@await Component.InvokeAsync("UserName",Param)  

src/Shop.Web/Pages/Shared/_UserNamePartialSitePanel.cshtml
@{
    var Param = new Shop.Application.DTOs.User.UserNameDto();
    if (User.Identity.IsAuthenticated)
    {
        Param.userName = User.Identity.Name;
    }
    else
    {
        Param.userName = null;
    }

    Param.Position = "SitePanel";
}
@await Component.InvokeAsync("UserName",Param)  