src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/DiscountPanel.cshtml.cs
using MediatR;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Parstech.Shop.Context.Application.DTOs.Paging;
using Parstech.Shop.Context.Application.DTOs.Product;
using Parstech.Shop.Context.Application.DTOs.ProductLog;
using Parstech.Shop.Context.Application.DTOs.ProductRepresentation;
using Parstech.Shop.Context.Application.DTOs.ProductStockPrice;
using Parstech.Shop.Context.Application.DTOs.Representation;
using Parstech.Shop.Context.Application.DTOs.RepresentationType;
using Parstech.Shop.Context.Application.DTOs.Response;
using Parstech.Shop.Context.Application.Features.ProductStockPrice.Requests.Commands;
using Parstech.Shop.Context.Application.Features.ProductStockPrice.Requests.Queries;
using Parstech.Shop.Context.Application.Features.ProductStockPriceSection.Requests.Commands;
using Parstech.Shop.Context.Application.Features.ProductStockPriceSection.Requests.Queries;
using Parstech.Shop.Context.Application.Features.Representation.Requests.Commands;
using Parstech.Shop.Context.Application.Features.RepresentationType.Requests.Commands;
using Parstech.Shop.Context.Application.Features.User.Requests.Queries;
using Parstech.Shop.Context.Application.Features.UserStore.Requests.Queries;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser,Inventory,Store")]
public class DiscountPanelModel : PageModel
{
    #region Constractor

    private readonly IMediator _mediator;

    public DiscountPanelModel(IMediator mediator)
    {
        _mediator = mediator; 
    }

    #endregion
    #region Properties

    //paging parameter
    [BindProperty]
    public ProductDiscountParameterDto Parameter { get; set; } = new();

    //categuries
    [BindProperty]
    public ProductDiscountPagingDto List { get; set; }


    //result
    [BindProperty]
    public ResponseDto Response { get; set; } = new();

    //Representations
    [BindProperty]
    public List<RepresentationDto> Representations { get; set; } = new();


    [BindProperty]
    public int RepId { get; set; }

    [BindProperty]
    public int productId { get; set; }

    [BindProperty]
    public ProductDto product { get; set; }

    [BindProperty]
    public ProductStockPriceDto productStock { get; set; }

    [BindProperty]
    public ProductRepresentationDto productRepresentation { get; set; }

    [BindProperty]
    public List<RepresentationTypeDto> repTypes { get; set; }


    [BindProperty]
    public ProductRepresentationDto ProductRepresentationDto { get; set; }

    //log
    [BindProperty]
    public LogDto LogDto { get; set; }

    [BindProperty]
    public PagingDto ProductLogPaging { get; set; }

    [BindProperty]
    public ParameterLogDto LogParameter { get; set; } = new();

    [BindProperty]
    public ProductRepresenationParameterDto PrParameter { get; set; } = new();

    public class logClass
    {
        public LogDto LogDto { get; set; }
        public PagingDto ProductLogPaging { get; set; }
        public List<ProductRepresenationChartDto> ProductRepresntationChart { get; set; }
        public PagingDto ProductRepresntationPaging { get; set; }
    }
    [BindProperty]
    public logClass Log { get; set; } = new();
    #endregion

    #region Get

    public async Task<IActionResult> OnGet()
    {
        Parameter.CurrentPage = 1;
        if (User.IsInRole("SupperUser"))
        {
            Representations = await _mediator.Send(new RepresentationReadsCommandReq());
        }
        else if (User.IsInRole("Store") || User.IsInRole("StoreBySend"))
        {
            var user = await _mediator.Send(new UserReadByUserNameQueryReq(User.Identity.Name));
            var userStore = await _mediator.Send(new UserStoreOfUserReadQueryReq(user.Id));
            var rep = await _mediator.Send(new RepresentationReadCommandReq(userStore.RepId));
            Representations.Add(rep);


        }
        else
        {
            Representations = await _mediator.Send(new RepresentationReadsCommandReq());
        }

        repTypes = await _mediator.Send(new RepresentationTypeReadsCommandReq());
        return Page();
    }

    public async Task<IActionResult> OnPostData()
    {

        Parameter.TakePage = 30;
        List = await _mediator.Send(new DiscountProductListPagingQueryReq(Parameter));
        Response.Object = List;
        Response.IsSuccessed = true;
            
        return new JsonResult(Response);
    }

        
    #endregion
    public async Task<IActionResult> OnPostGetSetionsOfProductStockPrice(int productStockPriceId)
    {
        var response= await _mediator.Send(new GetSectionOfProductStockPriceQueryReq(productStockPriceId));
        return new JsonResult(response);
    }
    public async Task<IActionResult> OnPostDeleteSetionsOfProductStockPrice(int ProductStockPriceSectionId,int ProductStockPriceId)
    {
        await _mediator.Send(new DeleteProdcutStockPriceSectionCommandReq(ProductStockPriceSectionId));
        var response = await _mediator.Send(new GetSectionOfProductStockPriceQueryReq(ProductStockPriceId));
        return new JsonResult(response);
    }
    public async Task<IActionResult> OnPostChangeShowInDiscountPanel(int ProductStockPriceSectionId,int isShow)
    {
        var item =await _mediator.Send(new ProductStockPriceReadCommandReq(ProductStockPriceSectionId));
        switch (isShow)
        {
            case 0:
                item.ShowInDiscountPanels = false; break;
            case 1:
                item.ShowInDiscountPanels = true; break;
        }
            
        var response= await _mediator.Send(new ProductStockPriceUpdateCommandReq(item));
        return new JsonResult(response);
    }

    public async Task<IActionResult> OnPostAddProductStockPriceSection(int ProductStockPriceSectionId, int sectionId)
    {
        await _mediator.Send(new CreateProdcutStockPriceSectionCommandReq(ProductStockPriceSectionId,sectionId));
        var response = await _mediator.Send(new GetSectionOfProductStockPriceQueryReq(ProductStockPriceSectionId));
        return new JsonResult(response);
            
    }
}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Sections.cshtml.cs
using MediatR;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Parstech.Shop.Context.Application.DTOs.Response;
using Parstech.Shop.Context.Application.DTOs.Section;
using Parstech.Shop.Context.Application.DTOs.SectionDetail;
using Parstech.Shop.Context.Application.Features.Section.Requests.Commands;
using Parstech.Shop.Context.Application.Features.Section.Requests.Queries;
using Parstech.Shop.Context.Application.Features.SectionDetail.Requests.Commands;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser")]
public class SectionsModel : PageModel
{
    #region Constractor

    private readonly IMediator _mediator;

    public SectionsModel(IMediator mediator)
    {
        _mediator = mediator;
    }

    #endregion

    #region Properties

    [BindProperty]
    public List<SectionAndDetailsDto> List { get; set; }

    [BindProperty]
    public SectionDto Section { get; set; }

    [BindProperty]
    public int SectionId { get; set; }


    [BindProperty]
    public SectionDetailDto SectionDetail { get; set; }

    [BindProperty]
    public int SectionDeatilId { get; set; }


    [BindProperty] public ResponseDto Response { get; set; } = new();
    #endregion

    #region Get

    public async Task<IActionResult> OnGet()
    {
        List = await _mediator.Send(new SectionAndDetailsReadsQueryReq(null));
        return Page();
    }

    //public async Task<IActionResult> OnPostGetAgain()
    //{
    //    List = await _mediator.Send(new SectionAndDetailsReadQueryReq());
    //    Response.Object = List;
    //    return new JsonResult(Response);
    //}

    public async Task<IActionResult> OnPostSection()
    {
        Section = await _mediator.Send(new SectionReadCommandReq(SectionId));
        Response.Object = Section;
        Response.IsSuccessed = true;
        return new JsonResult(Response);
    }

    public async Task<IActionResult> OnPostSectionDetail()
    {
        SectionDetail = await _mediator.Send(new SectionDetailReadCommandReq(SectionDeatilId));
        Response.Object = SectionDetail;
        Response.IsSuccessed = true;
        return new JsonResult(Response);
    }

    #endregion

    #region Create and Update

    public async Task<IActionResult> OnPostCreateUpdateSection()
    {
        if (SectionId != 0)
        {
            var result = await _mediator.Send(new SectionUpdateCommandReq(Section));
            Response.Object = result;
            Response.IsSuccessed = true;
            Response.Message = "ویرایش با موفقیت انجام شد";
            return new JsonResult(Response);
        }
        else
        {
            var result = await _mediator.Send(new SectionCreateCommandReq(Section));
            Response.Object = result;
            Response.IsSuccessed = true;
            Response.Message = "آیتم جدید با موفقیت افزوده شد";
            return new JsonResult(Response);
        }

    }

    public async Task<IActionResult> OnPostCreateUpdateSectionDetail()
    {

        if (SectionDeatilId != 0)
        {
            var result = await _mediator.Send(new SectionDetailUpdateCommandReq(SectionDetail));
            Response.Object = result;
            Response.IsSuccessed = true;
            Response.Message = "ویرایش با موفقیت انجام شد";
            return new JsonResult(Response);
        }
        else
        {
            SectionDetail.SectionId = SectionId;
            var result = await _mediator.Send(new SectionDetailCreateCommandReq(SectionDetail));
            Response.Object = result;
            Response.IsSuccessed = true;
            Response.Message = "آیتم جدید با موفقیت افزوده شد";
            return new JsonResult(Response);
        }

    }

    #endregion


    #region Delete

    public async Task<IActionResult> OnPostDeleteSection()
    {
        if (await _mediator.Send(new SectionCheckQueryReq(SectionId)))
        {
            await _mediator.Send(new SectionDeleteCommandReq(SectionId));
            Response.IsSuccessed = true;
            Response.Message = "آیتم با موفقیت حذف شد";
            return new JsonResult(Response);
        }
        else
        {
            Response.IsSuccessed = false;
            Response.Message = "تا زمانی که قسمت اصلی سایت دارای زیر مجموعه باشد امکان حذف آن وجود ندارد";
            return new JsonResult(Response);
        }


    }

    public async Task<IActionResult> OnPostDeleteSectionDetail()
    {
        var result = await _mediator.Send(new SectionDetailDeleteCommandReq(SectionDeatilId));
        Response.IsSuccessed = true;
        Response.Message = "آیتم با موفقیت حذف شد";
        return new JsonResult(Response);
    }

    #endregion

}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Seo.cshtml.cs
using MediatR;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Parstech.Shop.Context.Application.DTOs.Response;
using Parstech.Shop.Context.Application.DTOs.SiteSetting;
using Parstech.Shop.Context.Application.Features.SiteSeting.Requests.Commands;
using Parstech.Shop.Context.Application.Validators.SiteSetting;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser")]
public class SeoModel : PageModel
{
    private readonly IMediator _mediator;

    public SeoModel(IMediator mediator)
    {
        _mediator = mediator;
    }
    [BindProperty]
    public SeoDto Input { get; set; }


    [BindProperty] public ResponseDto Response { get; set; } = new();

    public async Task<IActionResult> OnGet()
    {
        Input = await _mediator.Send(new SeoSettingReadCommandReq(1));
        return Page();
    }

    public async Task<IActionResult> OnPost()
    {

        #region Validator
        var validator = new SeoDtoValidator();
        var valid = validator.Validate(Input);
        if (!valid.IsValid)
        {
            Response.IsSuccessed = false;
            Response.Errors = valid.Errors;
            Response.Object = Input;
            return new JsonResult(Response);
        }
        #endregion


        await _mediator.Send(new SeoSettingUpdateCommandReq(1, Input));
        Response.IsSuccessed = true;
        Response.Message = "ویرایش اطلاعات با موفقیت انجام شد";
        Response.Object = Input;

        return new JsonResult(Response);
    }
}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Shipping.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser")]
public class ShippingModel : PageModel
{
    public void OnGet()
    {
    }
}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Site.cshtml.cs
using MediatR;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Parstech.Shop.Context.Application.DTOs.Response;
using Parstech.Shop.Context.Application.DTOs.SiteSetting;
using Parstech.Shop.Context.Application.Features.SiteSeting.Requests.Commands;
using Parstech.Shop.Context.Application.Validators.SiteSetting;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser")]
public class SiteModel : PageModel
{

    private readonly IMediator _mediator;

    public SiteModel(IMediator mediator)
    {
        _mediator = mediator;
    }
    [BindProperty]
    public SiteDto Input { get; set; }


    [BindProperty] public ResponseDto Response { get; set; } = new();

    public async Task<IActionResult> OnGet()
    {
        Input = await _mediator.Send(new SiteSettingReadCommandReq(1));
        return Page();
    }

    public async Task<IActionResult> OnPost()
    {

        #region Validator
        var validator = new SiteDtoValidator();
        var valid = validator.Validate(Input);
        if (!valid.IsValid)
        {
            Response.IsSuccessed = false;
            Response.Errors = valid.Errors;
            Response.Object = Input;
            return new JsonResult(Response);
        }
        #endregion


        await _mediator.Send(new SiteSettingUpdateCommandReq(1, Input));
        Response.IsSuccessed = true;
        Response.Message = "ویرایش اطلاعات با موفقیت انجام شد";
        Response.Object = Input;

        return new JsonResult(Response);
    }
}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Social.cshtml.cs
using MediatR;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Parstech.Shop.Context.Application.DTOs.Response;
using Parstech.Shop.Context.Application.DTOs.SocialSetting;
using Parstech.Shop.Context.Application.Features.SocialSetting.Requests.Commands;
using Parstech.Shop.Context.Application.Validators.SocialSetting;

namespace Parstech.Shop.Web.Admin.Pages.Admin.Setting;

[Authorize(Roles = "SupperUser")]
public class SocialModel : PageModel
{
    private readonly IMediator _mediator;

    public SocialModel(IMediator mediator)
    {
        _mediator = mediator;
    }
    [BindProperty]
    public List<SocialSettingDto> List { get; set; }

    [BindProperty]
    public SocialSettingDto Input { get; set; }


    [BindProperty]
    public int Id { get; set; }


    [BindProperty] public ResponseDto Response { get; set; } = new();

    public async Task<IActionResult> OnGet()
    {
        List = await _mediator.Send(new SocialSettingListReadCommandReq());
        return Page();
    }
    public async Task<IActionResult> OnPostGetOne()
    {
        Input = await _mediator.Send(new SocialSettingReadCommandReq(Id));
        Response.Object = Input;
        Response.IsSuccessed = true;
        return new JsonResult(Response);
    }
    public async Task<IActionResult> OnPost()
    {

        #region Validator
        var validator = new SocialSettingDtoValidator();
        var valid = validator.Validate(Input);
        if (!valid.IsValid)
        {
            Response.IsSuccessed = false;
            Response.Errors = valid.Errors;
            Response.Object = Input;
            return new JsonResult(Response);
        }
        #endregion

        if (Input.Id != 0)
        {
            await _mediator.Send(new SocialSettingUpdateCommandReq(Input));
            Response.IsSuccessed = true;
            Response.Message = "شبکه اجتماعی با موفقیت ویرایش شد";
        }
        else
        {
            await _mediator.Send(new SocialSettingCreateCommandReq(Input));
            Response.IsSuccessed = true;
            Response.Message = "شبکه اجتماعی با موفقیت افزوده شد";
        }

        //Response.Object = Input;

        return new JsonResult(Response);
    }


}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/DiscountPanel.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Parstech.Shop.Web.Admin.Pages.Admin.Setting.DiscountPanelModel
@{
    Layout = "Shared/Admin_Layout";
}

<div class="row">
    <div class="col-lg-12">
        <div class="portlet box border shadow">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h3 class="title">
                        <i class="icon-settings"></i>
                        لیست کالای تخفیف دار
                    </h3>
                </div>
                @* <div class="button-box2">
                    <button class="btn btn-sm  btn-primary hover-green" onclick="CleanItem()" data-bs-toggle="modal" data-bs-target="#AddModal">
                        <i class="icon-plus"></i>
                        افزودن انبار جدید
                    </button>

                </div>*@

            </div>
            <div class="portlet box border shadow">
                <div class="portlet-heading">
                    <div class="portlet-title">
                        <h3 class="title">
                            جستجوی انبار
                        </h3>
                    </div><!-- /.portlet-title -->
                    <div class="buttons-box toggle toggle-mobile">
                    </div><!-- /.buttons-box -->
                </div><!-- /.portlet-heading -->
                <div class="portlet-body">
                    <form method="post" asp-page-handler="Data">

                        <div class="row">
                            <div class="col-lg-2">
                                <div class="form-group ">
                                    <label>فیلتر انبار</label>
                                    <select asp-for="RepId" id="RepId" onchange="DataSubmit()" class="form-control select2 round select2-hidden-accessible" tabindex="-1" aria-hidden="true">
                                        <option value="">انتخاب انبار</option>
                                        @foreach (var item in Model.Representations)
                                        {
                                            <option value="@item.Id">@item.Name</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group ">
                                    <label>فیلتر کالا </label>
                                    <select asp-for="Parameter.Filter" id="ProductsSelect" onchange="DataSubmit()" class="form-control round select2">
                                    </select>
                                </div>
                            </div>

                            <div class="col-lg-2">
                                <div class="form-group ">
                                    <label>دسته بندی ها</label>
                                    <select asp-for="Parameter.Categury" id="CategurySelect" onchange="DataSubmit()" class="form-control round select2">
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group ">
                                    <label>فیلتر پنل تخفیف</label>
                                    <select asp-for="Parameter.SectionId" id="SectionSelect" onchange="DataSubmit()" class="form-control round select2">
                                    </select>
                                </div>
                            </div>

                            <div class="col-lg-2">
                                <div class="form-group ">
                                    <label>فیلتر موجودی</label>
                                    <select asp-for="Parameter.Exist" id="ExistSelect" onchange="DataSubmit()" class="form-control select2">
                                        <option value="">انتخاب نشده</option>
                                        <option value="Exist">دارای موجودی</option>
                                        <option value="NotExist">عدم موجودی</option>

                                    </select>
                                </div>
                            </div>
                            @* <div class="col-lg-1">
                                <button type="submit" class="btn btn-blue text-white font-weight-bold mt-4 pt-2">فیلتر</button>
                            </div> *@

                        </div>
                    </form>
                    @* <form asp-page-handler="Data" method="post">
                        <div class="form-group">

                            <select asp-for="RepId" id="RepId" onchange="DataSubmit()" class="form-control select2 round select2-hidden-accessible" tabindex="-1" aria-hidden="true">
                                <option value="">انتخاب انبار</option>
                                @foreach (var item in Model.Representations)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </div>
                    </form> *@

                </div><!-- /.portlet-body -->
                <div class="portlet-body" style="">
                    <div class="d-flex mb-2" id="pagingHeader">
                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered " id="data-table">

                            <thead>
                                <tr>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                </tr>

                            </tbody>

                        </table>

                    </div>
                    <div class="d-flex mb-2" id="paging">
                    </div>
                </div><!-- /.portlet-body -->
            </div><!-- /.portlet -->
        </div><!-- /.portlet -->

    </div>

</div>

<!--FORMS-->
<form method="post" id="GetDataForm" asp-page-handler="Data"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="OnLoadingData"
      data-ajax-complete="OnCompleteData"
      data-ajax-failure="OnErrorData">
    <input type="hidden" asp-for="Parameter.RepId" class="RepId" />
    <input type="hidden" asp-for="Parameter.Filter" id="Parameter_Filter" />
    <input type="hidden" asp-for="Parameter.Categury" id="Parameter_Categury" />
    <input type="hidden" asp-for="Parameter.Exist" id="Parameter_Exist" />
    <input type="hidden" asp-for="Parameter.SectionId" id="Parameter_SectionId" />
    <input type="hidden" asp-for="Parameter.CurrentPage" id="Parameter_CurrentPage" />
</form>
<form method="post" id="GetSetionsOfProductStockPrice" asp-page-handler="GetSetionsOfProductStockPrice"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="OnLoadingGet"
      data-ajax-complete="OnCompleteGet"
      data-ajax-failure="OnErrorGet">
    <input type="hidden" name="productStockPriceId" class="productStockPriceId" />

</form>
<form method="post" id="DeleteSetionsOfProductStockPrice" asp-page-handler="DeleteSetionsOfProductStockPrice"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="OnCompleteChangeSection">
    <input type="hidden" name="ProductStockPriceSectionId" id="SectionId" />
    <input type="hidden" name="ProductStockPriceId" class="productStockPriceId" />

</form>
<form method="post" id="ChangeShowInDiscountPanelForm" asp-page-handler="ChangeShowInDiscountPanel"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="OnCompleteChange">
    <input type="hidden" name="ProductStockPriceSectionId" class="productStockPriceId" />
    <input type="hidden" name="isShow" id="isShow" />

</form>


<div id="Modal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close " data-bs-dismiss="modal">&times;</button>
                <h4 class="modal-title">ویرایش پنل تخفیف</h4>

            </div>
            <div class="modal-body">
                <div class="col-md-8 col-lg-6 m-auto" id="showInPanel">
                    
                </div>
                <div class="col-lg-12" id="addSection">
                    <form method="post" id="AddProductStockPriceSectionForm" asp-page-handler="AddProductStockPriceSection"
                          data-ajax="true"
                          data-ajax-method="POST"
                          data-ajax-complete="OnCompleteChangeSection">
                        <input type="hidden" name="ProductStockPriceSectionId" class="productStockPriceId" />
                        
                       
                        <div class="col-md-8 col-lg-6 m-auto ">
                            <div class="form-group ">
                                <label> پنل تخفیف</label>
                                <select name="sectionId" id="SectionSelect2" class="form-control round ">
                                </select>
                            </div>
                        </div>
                        <div class="col-md-8 col-lg-6 m-auto m-b-50">

                            <button type="submit" class="btn btn-info btn-round btn-block mb-2">
                                ثبت
                                <div class="paper-ripple">
                                    <div class="paper-ripple__background"></div>
                                    <div class="paper-ripple__waves"></div>
                                </div>
                            </button>
                        </div><!-- /.col-md-8 -->
                    </form>
                </div>
                <div class="col-lg-12" >
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped no-footer" id="data-table2" role="grid" aria-describedby="data-table2_info">

                            <thead>
                                
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="data-table2" rowspan="1" colspan="1" aria-label="نام ویژگی: activate to sort column descending" style="width: 345px;" aria-sort="ascending">نام ویژگی</th>
                                    <th class="w-50" tabindex="0" aria-controls="data-table2" rowspan="1" colspan="1" aria-label="عملیات: activate to sort column ascending" style="width: 345px;">عملیات</th>
                                </tr>
                            </thead>
                            <tbody id="sections">


                               

                        </table>

                    </div>
                </div>
                <div class="col-lg-12">
                </div><!-- /col-lg-12 -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-round" data-bs-dismiss="modal">بازگشت</button>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <link href="~/shared/lib/shared/toast/toast.css" rel="stylesheet" />
    <link href="~/Admin/plugins/data-table/DataTables-1.10.16/css/jquery.dataTables.css" rel="stylesheet">
    <link href="~/Admin/plugins/select2/dist/css/select2.min.css" rel="stylesheet">

}
@section Scripts {
    <script src="~/shared/lib/shared/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/shared/lib/shared/toast/toast.js"></script>
    <script src="~/shared/lib/shared/toast/mytoast.js"></script>

    <script src="~/Admin/plugins/data-table/js/jquery.dataTables.min.js"></script>
    <script src="~/shared/lib/shared/jquery-ajax-unobtrusive/3.2.6/separate.js"></script>

    @* <script src="~/shared/lib/admin/Representations/Index.js"></script> *@
    <script src="~/shared/lib/admin/setting/discountpanel.js"></script>

    <script src="~/Admin/plugins/select2/dist/js/select2.full.min.js"></script>
    <script src="~/Admin/plugins/select2/dist/js/i18n/fa.js"></script>
    <script src="~/Admin/js/pages/select2.js"></script>

    <script src="~/Admin/plugins/chart.js/dist/Chart.bundle.min.js"></script>

    @*<script src="~/Admin/js/pages/pie-chart.js"></script>*@
    @*<script src="~/Admin/js/pages/line-chart.js"></script>*@
    @* <script src="~/shared/lib/admin/Representations/Logs.js"></script> *@
    <script>

    </script>
}

src/Parstech.Shop.Web.Admin/Pages/Admin/Setting/Shipping.cshtml
@page
@model Parstech.Shop.Web.Admin.Pages.Admin.Setting.ShippingModel
@{
    Layout = "Shared/Admin_Layout";
}