src/Shop.Web/Pages/Admin/Brands/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.DTOs.Brand;
using Shop.Application.DTOs.Paging;
using Shop.Application.DTOs.Response;
using Shop.Application.Features.Brand.Requests.Commands;
using Shop.Application.Features.Brand.Requests.Queries;

namespace Shop.Web.Pages.Admin.Brands
{

    [Authorize(Roles = "SupperUser,Sale")]
    public class IndexModel : PageModel
    {
        #region Constractor

        private readonly IMediator _mediator;

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        #endregion

        #region Properties

        //paging parameter
        [BindProperty]
        public ParameterDto Parameter { get; set; } = new ParameterDto();

        //categuries
        [BindProperty]
        public PagingDto List { get; set; }

        //brand
        [BindProperty]
        public BrandDto BrandDto { get; set; }

        [BindProperty]
        public int BrandId { get; set; }

        //result
        [BindProperty]
        public ResponseDto Response { get; set; } = new ResponseDto();



        #endregion

        #region Get

        public async Task<IActionResult> OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostData()
        {

            Parameter.TakePage = 30;
            List = await _mediator.Send(new BrandsPagingQueryReq(Parameter));
            Response.Object = List;
            Response.IsSuccessed = true;

            return new JsonResult(Response);
        }

        #endregion

        #region Search Paging

        public async Task<IActionResult> OnPostSearch()
        {
            Parameter.CurrentPage = 1;
            Parameter.TakePage = 30;
            List = await _mediator.Send(new BrandsPagingQueryReq(Parameter));
            Response.Object = List;
            Response.IsSuccessed = true;
            return new JsonResult(Response);
        }

        public async Task<IActionResult> OnPostPaging()
        {
            Parameter.TakePage = 30;
            List = await _mediator.Send(new BrandsPagingQueryReq(Parameter));
            Response.Object = List;
            Response.IsSuccessed = true;
            return new JsonResult(Response);
        }

        #endregion
        #region Add Or EditCategury

        public async Task<IActionResult> OnPostItem()
        {
            BrandDto = await _mediator.Send(new BrandReadCommandReq(BrandId));
            Response.Object = BrandDto;
            return new JsonResult(Response);
        }

        public async Task<IActionResult> OnPostEditOrCreate()
        {
            if (BrandDto.BrandId != 0)
            {
                BrandDto.ChangeByUserName = User.Identity.Name;
                BrandDto.LastChangeTime = DateTime.Now;
                BrandDto.IsDelete = false;
                await _mediator.Send(new BrandUpdateCommandReq(BrandDto));
                Response.Object = BrandDto;
                Response.IsSuccessed = true;
                Response.Message = "برند با موفقیت ویرایش شد";
                return new JsonResult(Response);
            }
            else
            {
                BrandDto.ChangeByUserName = User.Identity.Name;
                BrandDto.LastChangeTime = DateTime.Now;
                BrandDto.IsDelete = false;
                await _mediator.Send(new BrandCreateCommandReq(BrandDto));
                Response.Object = BrandDto;
                Response.IsSuccessed = true;
                Response.Message = "برند با موفقیت ثبت شد";
                return new JsonResult(Response);
            }
        }
        #endregion
    }
}

src/Shop.Web/Pages/Admin/Products/CreateOrUpdateAjax/Categuries.cshtml.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Contracts.Persistance;
using Shop.Application.DTOs.ProductCategury;
using Shop.Application.DTOs.ProductGallery;
using Shop.Application.DTOs.Response;
using Shop.Application.Features.Categury.Requests.Commands;
using Shop.Application.Features.Product.Requests.Commands;
using Shop.Application.Features.Product.Requests.Queries;
using Shop.Application.Features.ProductCategury.Requests.Commands;
using Shop.Application.Features.ProductGallery.Requests.Queries;
using Shop.Application.Features.ProductStockPrice.Requests.Commands;
using Shop.Application.Features.ProductStockPrice.Requests.Queries;
using Shop.Domain.Models;
using System.Threading.Tasks;


namespace Shop.Web.Pages.Admin.Products.CreateOrUpdateAjax
{
    public class CateguriesModel : PageModel
    {
        #region Constractor

        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly IProductStockPriceRepository _productStockRep;


        public CateguriesModel(IMediator mediator,
            IMapper mapper,
            IProductStockPriceRepository productStockRep)
        {
            _mediator = mediator;
            _mapper = mapper;
            _productStockRep = productStockRep;
        }

        #endregion
        //id
        [BindProperty] public int? productId { get; set; }


        //product
        [BindProperty] public List<ProductCateguryDto> Categuries { get; set; }

        [BindProperty] public ProductCateguryDto categury { get; set; }

        [BindProperty] public List<ProductCateguryDto> categuries { get; set; }

        //result
        [BindProperty] public ResponseDto Response { get; set; } = new ResponseDto();

        [BindProperty] public string FilterCat { get; set; }

        public async Task OnGet(int? id)
        {
            productId = id;
            if (productId != null)
            {
                Categuries = await _mediator.Send(new CateguriesOfProductQueryReq(productId.Value));
            }
        }



        #region Categury

        public async Task<IActionResult> OnPostGetAllCateguries()
        {
            var categuries = await _mediator.Send(new CateguryReadCommandReq(FilterCat));
            Response.Object = categuries;
            Response.IsSuccessed = true;
            return new JsonResult(Response);
        }

        public async Task<IActionResult> OnPostCateguries()
        {
            categuries = await _mediator.Send(new CateguriesOfProductQueryReq(productId.Value));
            Response.Object = categuries;
            return new JsonResult(Response);
        }

        public async Task<IActionResult> OnPostCategury()
        {
            categury = await _mediator.Send(new CateguryOfProductQueryReq(productId.Value));
            Response.Object = categury;
            return new JsonResult(Response);
        }

        public async Task<IActionResult> OnPostDeleteCategury()
        {
            var ProductId = await _mediator.Send(new ProductCateguryDeleteCommandReq(productId.Value));
            Response.Object = ProductId;
            Response.IsSuccessed = true;
            return new JsonResult(Response);
        }


        

        #endregion
    }
}

src/Shop.Web/Pages/Admin/Products/CreateOrUpdateAjax/ChildsAndStock.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Contracts.Persistance;
using Shop.Application.DTOs.Product;
using Shop.Application.DTOs.ProductProperty;
using Shop.Application.DTOs.ProductStockPrice;
using Shop.Application.Features.Product.Requests.Commands;
using Shop.Application.Features.Product.Requests.Queries;
using Shop.Application.Features.ProductProperty.Requests.Queries;
using Shop.Application.Features.User.Requests.Queries;
using Shop.Application.Features.UserStore.Requests.Queries;

namespace Shop.Web.Pages.Admin.Products.Detail
{
    public class ChildsAndStockModel : PageModel
    {
        #region Constractor

        private readonly IMediator _mediator;

        private readonly IProductStockPriceRepository _productStockRep;


        public ChildsAndStockModel(IMediator mediator,

            IProductStockPriceRepository productStockRep)
        {
            _mediator = mediator;

            _productStockRep = productStockRep;
        }

        #endregion
        //id
        [BindProperty] public int? productId { get; set; }
        [BindProperty] public int? TypeId { get; set; } = 0;

        public ChildsAndStock ChildsAndStock { get; set; }
        public ProductDto product { get; set; }

        public async Task OnGet(int? id)
        {
            productId = id;
            if (productId != 0)
            {
                product = await _mediator.Send(new ProductReadCommandReq(id.Value));
                TypeId = product.TypeId;
            }
            if (User.IsInRole("Store") || User.IsInRole("StoreBySend"))
            {
                var user = await _mediator.Send(new UserReadByUserNameQueryReq(User.Identity.Name));
                var userStore = await _mediator.Send(new UserStoreOfUserReadQueryReq(user.Id));
                ChildsAndStock =
                    await _mediator.Send(new GetChildsAndProductStocksQueryReq(productId.Value, userStore.Id));

                
            }
            else
            {
                ChildsAndStock =
                    await _mediator.Send(new GetChildsAndProductStocksQueryReq(productId.Value, 0));
            }
        }
    }
}

src/Shop.Web/Pages/Products/Credit.cshtml.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Drawing.Charts;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Shop.Application.DTOs.Api;
using Shop.Application.DTOs.CreditProductStockPrice;
using Shop.Application.DTOs.Product;
using Shop.Application.DTOs.ProductCategury;
using Shop.Application.DTOs.ProductGallery;
using Shop.Application.DTOs.Response;
using Shop.Application.Features.Api.Requests.Queries;
using Shop.Application.Features.CreditProductStockPrice.Requests.Queries;
using Shop.Application.Features.Order.Requests.Queries;
using Shop.Application.Features.OrderShipping.Request.Queries;
using Shop.Application.Features.Product.Requests.Queries;
using Shop.Application.Features.ProductGallery.Requests.Queries;
using Shop.Domain.Models;

namespace Shop.Web.Pages.Products
{
    public class CreditModel : PageModel
    {
        #region Constractor

        private readonly IMediator _mediator;

        public CreditModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        #endregion

        #region Properties

        //result
        [BindProperty]
        public ResponseDto Response { get; set; } = new ResponseDto();


        
        public List<CreditProductStockPriceDto>? Items { get; set; }


        [BindProperty]
        public CreditProductStockPriceDto? Credit { get; set; } 


        
        public string ShortLink { get; set; }

        #endregion

        #region Get

        public async Task<IActionResult> OnGet(string shortLink)
        {
            ShortLink = shortLink;
            #region Get User If Authenticated
            var userName = "";
            if (User.Identity.IsAuthenticated)
            {
                userName = User.Identity.Name;
            }
            else
            {
                userName = null;
            }
            #endregion
            Items = await _mediator.Send(new GetCreditProductStockPriceByProductShortlinkQueryReq(ShortLink));
            return Page();
        }
        public async Task<IActionResult> OnPostComplete()
        {
            var creditProduct = await _mediator.Send(new GetCreditProductStockPriceQueryReq(Credit.Id,Credit.ProductStockPriceId)); 
            var order = await _mediator.Send(new CreateCheckoutForCreditProductQueryReq(User.Identity.Name, creditProduct)); 
            
            if(order.OrderId==0 || order.OrderId == null)
            {
                ResponseDto response = new ResponseDto();
                response.IsSuccessed = false;
                response.Message = "تا زمانی که اقساط اعتباری پرداخت نشده دارید امکان ثبت خرید جدید وجود ندارد";
                return new JsonResult(Response);
            }
            var shipping=await _mediator.Send(new OrderShippingChangeQueryReq("Change", 0, order.OrderId, 0));
            var payTypeId = 0;
            if (Credit.PrePay > 0)
            {
                payTypeId = 7;
            }
            else{
                payTypeId = 8;
            }
            var orrderShipping= await _mediator.Send(new OrderShippingGetByOrderIdQueryReq(order.OrderId));
            Response = await _mediator.Send(new CompleteOrderForCreditProductQueryReq(order.OrderId, orrderShipping.Id, payTypeId, creditProduct));
            return new JsonResult(Response);
        }



        #endregion
    }
}

src/Shop.Web/ViewComponents/StorePageSectionViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.DTOs.Product;
using Shop.Application.DTOs.Section;
using Shop.Application.Features.Brand.Requests.Commands;
using Shop.Application.Features.Product.Requests.Commands;
using Shop.Application.Features.Product.Requests.Queries;
using Shop.Application.Features.Section.Requests.Queries;

namespace Shop.Web.ViewComponents
{
    [ViewComponent(Name = "StorePageSection")]
    public class StorePageSectionViewComponent : ViewComponent
    {

        private readonly IMediator _mediator;
        public StorePageSectionViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IViewComponentResult> InvokeAsync(string store)
        {
            int Take = 9;
            int DiscountTake = 20;
            var Item = await _mediator.Send(new SectionAndDetailsReadStoreQueryReq(store));

            switch (Item.SectionTypeId)
            {
                case 1:
                    SliderShowDto slider = new SliderShowDto();
                    List<SectionDetailShowDto> desktop = new List<SectionDetailShowDto>();
                    List<SectionDetailShowDto> mobile = new List<SectionDetailShowDto>();
                    foreach (var slide in Item.SectionDetails)
                    {
                        if (slide.ResponsiveSize == "Mobile")
                        {
                            mobile.Add(slide);
                        }
                        else
                        {
                            desktop.Add(slide);
                        }
                    }
                    slider.Desktop = desktop;
                    slider.Mobile = mobile;
                    return View("SlideShow", slider);

                case 2:
                    if (Item.CateguryId != 0)
                    {
                        ProductSearchParameterDto parameter = new ProductSearchParameterDto();
                        parameter.CateguryId = Item.CateguryId;
                        parameter.Take = 10;
                        #region Get User If Authenticated
                        var userName = "";
                        if (User.Identity.IsAuthenticated)
                        {
                            userName = User.Identity.Name;
                        }
                        else
                        {
                            userName = null;
                        }
                        #endregion'
                        var pagingItem = await _mediator.Send(new IntegratedProductsPagingQueryReq(parameter,userName));
                        Item.ProductCateguries = pagingItem.ProductList;
                        //Item.ProductCateguries = await _mediator.Send(new GetSomeOfLastProductsByCateguryIdQueryReq(Take, Item.CateguryId));
                        Item.latinCateguryName = Item.ProductCateguries.First().CateguryLatinName;
                    }
                    return View("ListProducts", Item);

                case 3:

                    Item.ProductCateguries = await _mediator.Send(new GetProductsWithDiscountQueryReq(DiscountTake,Item.Id));

                    if (Item.ProductId != 0)
                    {
                        Item.Product = await _mediator.Send(new ProductReadCommandReq(Item.ProductId));
                    }
                    return View("Discount", Item);
                case 4: return View("TwoBanner", Item);
                case 5: return View("SixBanner", Item);
                case 6: return View("LargeBanner", Item);
                case 7: return View("Icons", Item);
                case 8:
                    if (Item.CateguryId != 0)
                    {
                        Item.latinCateguryName = Item.ProductCateguries.First().CateguryLatinName;
                    }
                    return View("CateguryIcons", Item);
                case 9:
                    Item.Brands = await _mediator.Send(new BrandReadsCommandReq());
                    return View("BrandSlider", Item);
            }
            return View("Default");
        }
    }
}

src/Shop.Web/Pages/Products/Credit.cshtml
@page "{shortLink}"
@model Shop.Web.Pages.Products.CreditModel
@{
}
<main id="content" role="main">
    <div class="container ">
        <div class="row">
            <partial name="Site/_PanelSideBar" />

            <div class="col-lg-9 order-lg-1 rtl">
                <div class="pb-7 mb-7">
                    <!-- Title -->
                    <div class="panel panel-warning box shadow border">
                        <div class="panel-heading">
                            <div class="panel-title ">
                                <h6 class="title">

                                    شرایط خرید اعتباری
                                    
                                    
                                </h6>
                                @if(Model.Items.Count>0){
                                    <strong>@Model.Items.FirstOrDefault().Name</strong>
                                }
                            </div><!-- /.panel-title -->
                            <div class="buttons-box toggle">
                            </div><!-- /.buttons-box -->
                        </div><!-- /.panel-heading -->
                       
                        <div class="row mt-2">
                            @foreach(var item in Model.Items){
                                <div class="col-lg-6 col-12">
                                <div class="card">
                                    <div class="card-header">
                                            <h1 class="badge font-size-17 BgBlue font-weight-bold">@item.Month ماهه</h1>
                                    </div>
                                    <div class="card-body text-center">
                                        <h5 class="font-weight-bold">کالا</h5>
                                        <h6>@item.Name </h6>
                                        
                                        <h5 class="font-weight-bold">مدل</h5>
                                        <h6>@item.VariationName</h6>
                                        
                                        <h5 class="font-weight-bold">قیمت محصول</h5>
                                            <h6>  @item.SalePrice.ToString("0,#")  تومان </h6>
                                        
                                        <h5 class="font-weight-bold">میزان سود محاسبه شده</h5>
                                        <h6>@item.Persent %</h6>
                                        
                                        <h5 class="font-weight-bold">مبلغ قابل پرداخت ماهیانه</h5>
                                            <h6>  @item.PayMonth.ToString("0,#") تومان</h6>
                                        
                                        <h5 class="font-weight-bold">مبلغ پیش پرداخت </h5>
                                            <h6>  @item.PrePay.ToString("0,#") تومان</h6>
                                        
                                        <h5 class="font-weight-bold">مبلغ نهایی  </h5>
                                            <h6>  @item.Total.ToString("0,#") تومان</h6>
                                    </div>
                                    <div class="card-foote">

                                            <button type="button" onclick="AcceptCredit(@item.Id,@item.ProductStockPriceId)" class="btn BgBlue text-white  btn-block " data-bs-toggle="modal" data-bs-target="#CreditModal">
                                                درخواست خرید اعتباری
                                                <div class="paper-ripple">
                                                    <div class="paper-ripple__background"></div>
                                                    <div class="paper-ripple__waves"></div>
                                                </div>
                                            </button>
                                        </div>

                                    </div>
                                </div>
                           
                            }
                        </div>
                    </div>
                    <!-- End Title -->




                </div>
            </div>
        </div>

    </div>
</main>

<div id="CreditModal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close " data-bs-dismiss="modal">&times;</button>
                <h4 class="modal-title">تایید خرید اعتباری</h4>
                
            </div>
            <div class="modal-body">
                <div class="col-lg-12 text-center">
                    <h4>آیا از ثبت درخواست خود اطمینان دارید؟</h4>
                    <h5>با تایید درخواست سفارش شما ثبت و اقساط شما محاسبه میگردد.</h5>
                    <form method="post"  asp-page-handler="Complete"
                          data-ajax="true"
                          data-ajax-method="POST"
                          data-ajax-begin="OnLoadingCredit"
                          data-ajax-complete="OnCompleteCredit">
                        <input type="hidden" asp-for="Credit.Id" id="Credit_Id" />
                        <input type="hidden" asp-for="Credit.ProductStockPriceId" id="Credit_ProductStockPriceId" />
                        
                        <button type="submit" class="btn btn-sm btn-success btn-round hover-green">تایید درخواست</button>
                    </form>

                </div><!-- /col-lg-12 -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-round" data-bs-dismiss="modal">بازگشت</button>
            </div>
        </div>
    </div>
</div>

<!--FORMS-->



@section Styles {
    <link href="~/Shared/Lib/Shared/Toast/Toast.css" rel="stylesheet" />
    <link href="~/Admin/plugins/data-table/DataTables-1.10.16/css/jquery.dataTables.css" rel="stylesheet">
    <link href="~/Admin/plugins/select2/dist/css/select2.min.css" rel="stylesheet">

    <link href="~/Site/ProductDetail/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/Site/ProductDetail/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Site/ProductDetail/main.css" rel="stylesheet" />
}
@section Scripts {
    <script src="~/Shared/Lib/Shared/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Shared/Lib/Shared/Toast/Toast.js"></script>
    <script src="~/Shared/Lib/Shared/Toast/MyToast.js"></script>


    <script src="~/Shared/Lib/Shared/jquery-ajax-unobtrusive/3.2.6/Separate.js"></script>

    <script src="~/Shared/Lib/Site/Products/Credit.js"></script>
}

src/Shop.Web/Pages/Products/Stores.cshtml
@page "{store}"
@model Shop.Web.Pages.Products.StoresModel
@{
}

<main class="rtl"  id="content" role="main">
    <!-- breadcrumb -->
    <!-- End breadcrumb -->
    
    
    <div class="container">
        <div class="row mb-8 rtl">
           
            

            <div class="col-xl-12 col-wd-12gdot6">
                <div class="ltr ">


                    @await Component.InvokeAsync("StorePageSection",Model.Store)




                </div>
            </div>
            <div class="col-xl-12 ">
                

                <!-- Shop-control-bar Title -->
                <div class="d-block d-md-flex flex-center-between ">
                    <nav aria-label="">
                        <div class="breadcrumb  ">
                            <a href="/">فروشگاه پارس تک</a><i class=" ec ec-arrow-right-categproes p-1"></i>
                            <a href="/">پنل تامین کننده</a><i class=" ec ec-arrow-right-categproes p-1"></i>
                            <a class=" " aria-current="page" id="StoreName"></a>
                            
                        </div>
                    </nav>
                    @*<h5 class="mb-2 mb-md-0">محصولات پــارس تـــک</h5>*@
                    <div class="d-flex mb-2" id="pagingHeader">
                    </div>

                </div>
                <!-- End shop-control-bar Title -->
                <!-- Shop-control-bar -->
                <div class="bg-gray-1 flex-center-between borders-radius-9 py-1">
                    <div class="d-xl-none">
                        <!-- Account Sidebar Toggle Button -->
                        <a id="sidebarNavToggler1" class="btn btn-sm py-1 font-weight-normal" href="javascript:;" role="button"
                           aria-controls="sidebarContent1"
                           aria-haspopup="true"
                           aria-expanded="false"
                           data-unfold-event="click"
                           data-unfold-hide-on-scroll="false"
                           data-unfold-target="#sidebarContent1"
                           data-unfold-type="css-animation"
                           data-unfold-animation-in="fadeInLeft"
                           data-unfold-animation-out="fadeOutLeft"
                           data-unfold-duration="500">
                            <i class="fas fa-sliders-h"></i> <span class="ml-1">Filters</span>
                        </a>
                        <!-- End Account Sidebar Toggle Button -->
                    </div>
                    <div class="px-3 d-none d-xl-block">
                        <ul class="nav nav-tab-shop" id="pills-tab" role="tablist">
                            <li class="nav-item m-1">
                                <a class="nav-link active" id="pills-one-example1-tab" data-toggle="pill" href="#pills-one-example1" role="tab" aria-controls="pills-one-example1" aria-selected="false">
                                    <div class="d-md-flex justify-content-md-center align-items-md-center">
                                        <i class="fa fa-th"></i>
                                    </div>
                                </a>
                            </li>

                            <li class="nav-item m-1">
                                <a class="nav-link" id="pills-four-example1-tab" data-toggle="pill" href="#pills-four-example1" role="tab" aria-controls="pills-four-example1" aria-selected="true">
                                    <div class="d-md-flex justify-content-md-center align-items-md-center">
                                        <i class="fa fa-th-list"></i>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="d-flex" id="TypeSection">
                        </div>

                </div>
                <!-- End Shop-control-bar -->
                <!-- Shop Body -->
                <!-- Tab Content -->
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade pt-2 show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab" data-target-group="groups">
                        <ul class="row list-unstyled products-group no-gutters"id="ProdcutsSection">
                            </ul>
                    </div>

                    <div class="tab-pane fade pt-2" id="pills-four-example1" role="tabpanel" aria-labelledby="pills-four-example1-tab" data-target-group="groups">
                        <ul class="d-block list-unstyled products-group prodcut-list-view-small" id="productListSection">
                            
                        </ul>
                    </div>
                </div>
                <!-- End Tab Content -->
                <!-- End Shop Body -->
                <!-- Shop Pagination -->
               
                <div onscroll="show()" id="PagingScroll">
                    <button class="btn btn-default pointer text-center" onclick="loadMoreItems()">مشاهده موارد بیشتر</button>
                </div>
                <!-- End Shop Pagination -->
            </div>
        </div>
       
    </div>
</main>




<form method="post" id="GetDataForm" asp-page-handler="Data"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="OnLoadingData"
      data-ajax-complete="OnCompleteData"
      data-ajax-failure="OnErrorData">
    <input type="hidden" asp-for="Store" id="Store" />
    
    <input type="hidden" asp-for="Parameter.Store" id="Parameter_Store" />
    
    <input type="hidden" asp-for="Parameter.Filter" id="Parameter_Filter" />
    
</form>

@section Styles {
    <link href="~/Shared/Lib/Shared/Toast/Toast.css" rel="stylesheet" />
    <link href="~/Admin/plugins/data-table/DataTables-1.10.16/css/jquery.dataTables.css" rel="stylesheet">
    <link href="~/Admin/plugins/select2/dist/css/select2.min.css" rel="stylesheet">
}
@section Scripts {
    <script src="~/Shared/Lib/Shared/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Shared/Lib/Shared/Toast/Toast.js"></script>
    <script src="~/Shared/Lib/Shared/Toast/MyToast.js"></script>


    <script src="~/Shared/Lib/Shared/jquery-ajax-unobtrusive/3.2.6/Separate.js"></script>

    <script src="~/Shared/Lib/Site/Products/Stores.js"></script>

}